### ISSUE TITLE
Error compiling example

### ISSUE THREAD

**Issue by nvangs** [monkeyboard/Wiegand-Protocol-Library-for-Arduino#14]
Hi,
Im getting this error when trying to compile your example:

```
\Arduino\libraries\Wiegand-Protocol-Library-for-Arduino-master\Wiegand.cpp: In member function 'void WIEGAND::begin()':
\Arduino\libraries\Wiegand-Protocol-Library-for-Arduino-master\Wiegand.cpp:37: error: 'NOT_AN_INTERRUPT' was not declared in this scope
```
Can you help me? Thanks.

**Comment by monkeyboard** [comment]
Hi,

I don't have access to a computer now, try to rename your library name
following our readme. It should be arduino/libraries/wiegand

The current folder of yours has a very long name and I presume you
downloaded the zip file directly from github.

Hope this helps.

Cheers
JP

**Comment by nvangs** [comment]
Hi JP,

Thanks for your reply. Renaming the library didn't help.

```
C:\Arduino\libraries\wiegand\Wiegand.cpp: In member function 'void WIEGAND::begin()':
C:\Arduino\libraries\wiegand\Wiegand.cpp:37: error: 'NOT_AN_INTERRUPT' was not declared in this scope
```

**Comment by monkeyboard** [comment]
Check this out.

**Comment by monkeyboard** [comment]
https://forum.arduino.cc/index.php?topic=353602.0

**Comment by nvangs** [comment]
It did the trick! 

Thanks for a great library!
