### ISSUE TITLE
Configuring GPIO PIN for ESP32 ?

### ISSUE THREAD

**Issue by Netoperz** [monkeyboard/Wiegand-Protocol-Library-for-Arduino#20]
Any idea how to use this library with ESP32 ?

I do not know how to remap pins to proper pins that i have free on my board, and can any pin be used for input from wiegand reader ?

**Comment by nardev** [comment]
for ESP8266 it was ok when i started it like

```
wg.begin(4,4,5,5);
```

where 4 and 5 is D0 and D1

ESP8266 has interrupts on all pins so.. it's not like arduino...

**Comment by jpliew** [comment]
@Netoperz did @nardev 's answer work for you? Please let me know so that I can close this issue.
