### ISSUE TITLE
Is it possible to add onReceive like method?

### ISSUE THREAD

**Issue by nardev** [monkeyboard/Wiegand-Protocol-Library-for-Arduino#22]
Is it possible to add something like "onReceive" so that you can attach call back functions what to do with read...

**Comment by IfollowU** [comment]
Is it possible to use 2 instances i.e ( wg and wg2)? It is possible to use 2 instance as per tested with ESP8266, but randomly show IN or OUT at any reader swiped. They are separated when swiped.

 codes:-

if (wg.available())
  {
    String tagId =  String(wg.getCode(), HEX);
    tagId.toUpperCase();
    String data = sysId + "," + epoch + "," + tagId + "," + "IN";
    //Serial.print(data);
    sendmsg(data);

  }
  if (wg2.available())
  {
    String tagId =  String(wg2.getCode(), HEX);
    tagId.toUpperCase();
    String data = sysId + "," + epoch + "," + tagId + "," + "OUT";
    //Serial.print(data);
    sendmsg(data);
  }
