### ISSUE TITLE
Last commit broke the user page

### ISSUE THREAD

**Issue by nardev** [monkeyboard/Wiegand-Protocol-Library-for-Arduino#25]
Unfortunately, last commits broke the user page. It just stops at a message:

"You can add new users by either scanning a RFID Tag or by clicking on "New User" button."

And there is no add button to be shown etc..

please check, i have Wiegand version waiting for that. It's tested, works fine.. but this  is confusing :(

**Comment by jpliew** [comment]
@nardev are you sure you are reporting an issue related to this library?

**Comment by nardev** [comment]
So ooo sooorrryyy.. Wrong repo... It was open...
