### ISSUE TITLE
It doesn't work on ESP32-EVB

### ISSUE THREAD

**Issue by GeorgeFlorian** [monkeyboard/Wiegand-Protocol-Library-for-Arduino#44]
Board: Olimex ESP32-EVB

I am trying to read a 26 bit card using a Card Reader. I have got a list of available pins from Olimex and I have tried some pins, but I get no output.

The code is basic:
```
#include <Arduino.h>
#include <Wiegand.h>

#define W0 13
#define W1 17

WIEGAND wg;

void setup() {
  Serial.begin(115200);
  wg.begin(W0,W1);
  Serial.println("------------------------------------");
  Serial.println(digitalRead(W0));
  Serial.println(digitalRead(W1));
}

void loop() {
  if(wg.available()) {
    Serial.println("wg.available()");

    Serial.print("Wiegand HEX = ");
    Serial.print(wg.getCode(),HEX);
    Serial.print(", DECIMAL = ");
    Serial.print(wg.getCode());
    Serial.print(", Type W");
    Serial.println(wg.getWiegandType());    
  }
}
```

The above pins are:
```
ESP32-WROOM-32D#16 - GPIO13/I2C-SDA - EXT1#14 - UEXT1#6 (pulled-up to 3.3V via 2.2k)
ESP32-WROOM-32D#28 - GPIO17/SPI_CS - EXT1#18 - UEXT1#10 (pulled-up to 3.3V via 10k)
```

The card reader is a SVTech X-STAL.

What do you think ? I've tried reversing the pins, but still no output.

Also, is there a way of mimicking reading a card by sending data to the reader using the ESP ? So, instead of using a card, I send the 26 bit code to the reader as if a card was used.

**Comment by jpliew** [comment]
Hi @GeorgeFlorian , 

Before using the library, it is best to check if the reader is sending out the Wiegand signal.

1. Make sure that the reader is being powered according to the manufacturer's specs
2. Use a scope to check if the D0 and D1 are sending out pulses
3. Make sure you have a 5v to 3.3v voltage level converter from D0/D1 to the pins of ESP32
