### ISSUE TITLE
Esp 32 working for a while, not stable

### ISSUE THREAD

**Issue by Ezenu** [monkeyboard/Wiegand-Protocol-Library-for-Arduino#52]
Hi!! I have two RFIDs working, they work for a random period and it stops working, I use the double core, and the library is in the main core as well as its operation, everything else works correctly and stable, also the connections and data sending by Wi-Fi, has it happened to someone else, or can I stabilize it?

**Comment by monkeyboard** [comment]
Hi,

This library is not designed for multiple readers, it will definitely work
but it produces incorrect data.

It is hard to understand what went wrong when you just said not working.
Not working has a very wide meaning without seeing your code.

How good the other things like WIFI and data sending are not relevant to
the troubleshooting of this library.
