### ISSUE TITLE
Arduino Uno Wiegand 34, not Working

### ISSUE THREAD

**Issue by fajruliqbalmubarok** [monkeyboard/Wiegand-Protocol-Library-for-Arduino#55]
Not Respon In Arduino Uno with Wiegand-34 13.56 MHz Procimity.  code is no correct but if I scan the card no respon in Serial Print

**Comment by jpliew** [comment]
Maybe it will be easier for people to help you if you can explain clearly with diagram or photo of your setup showing and also the brand and model of your reader.

I am also confused when you said no respon and code is not correct. If there was no response, how do you know the code is not correct?

**Comment by fajruliqbalmubarok** [comment]
ok tanks for answer. i can do, but if  upload i  board sometimes error in line wg.begin(). sometimes is not, and can i get uid same with mifare reader usb?

**Comment by jpliew** [comment]
Hi @fajruliqbalmubarok without showing what error you saw with `wg.begin()` it will be challenging for someone to figure out how to help you.
