### ISSUE TITLE
Is it possible to read card ID and memory?

### ISSUE THREAD

**Issue by mrNo0b** [monkeyboard/Wiegand-Protocol-Library-for-Arduino#64]
I use this library, everything works fine, but I would also like to read data that I write to the cards/tags.
Is it even possible with WG?
Do I have to buy specific WG RFID reader or everyone can read memory?
I don't know much about Wiegand protocol and RFID that why I ask,,,

**Comment by jpliew** [comment]
Hi @mrNo0b 

The Wiegand RFID reader will only output the card ID. 

To read data written into user area, you need RFID reader like this

13.56Mhz https://www.google.com/search?client=firefox-b-d&q=MFRC522

**Comment by mrNo0b** [comment]
Thank you for the info!

I use this:
![wgrfid](https://user-images.githubusercontent.com/12209347/207036011-63edc878-4bdf-4c07-8ec5-18e0b04f4134.png)

I also have MFRC522 but the problem is that this board is not exactly "production ready" I will need some case for it and it requires too many wires instead of D0 and D1...😢
